{% set name = "juliaup" %}
{% set version = "1.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JuliaLang/{{ name }}/archive/v{{ version }}.zip
  sha256: d145088d94f9c511b321e89f522bd18ea82ac634cd1e99081badf580cfc89298

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --root "$PREFIX" --path .  # [unix]
    - cargo install --locked --root "%LIBRARY_PREFIX%" --path . || goto :error  # [win]
    - rm -f "${PREFIX}/.crates.toml"  # [unix]
    - del /F /Q "%LIBRARY_PREFIX%\.crates.toml"  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - juliaup status

about:
  home: https://github.com/JuliaLang/juliaup
  summary: Julia installer and version multiplexer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mkitti
    - ngam
