{% set name = "juliaup" %}
{% set version = "1.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JuliaLang/{{ name }}/archive/v{{ version }}.zip
  sha256: 63ef0e88f0633210d7ec65bb6d42f4d5f101f37780c341db18311f5047752cc1

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --root "$PREFIX" --path .  # [unix]
    - cargo install --locked --root "%LIBRARY_PREFIX%" --path . || goto :error  # [win]
    - rm -f "${PREFIX}/.crates.toml"  # [unix]
    - del /F /Q "%LIBRARY_PREFIX%\.crates.toml"  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:

test:
  commands:
    - juliaup status

about:
  home: https://github.com/JuliaLang/juliaup
  summary: Julia installer and version multiplexer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mkitti
    - ngam
