{% set name = "juliaup" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JuliaLang/{{ name }}/archive/v{{ version }}.zip
  sha256: de27fe2984799fc9f4459c5d65bcb81b79720369c4097b243c6f127b01ec61d6

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --root "$PREFIX" --path .  # [unix]
    - cargo install --locked --root "%LIBRARY_PREFIX%" --path . || goto :error  # [win]
    - rm -f "${PREFIX}/.crates.toml"  # [unix]
    - del /F /Q "%LIBRARY_PREFIX%\.crates.toml"  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - juliaup status

about:
  home: https://github.com/JuliaLang/juliaup
  summary: Julia installer and version multiplexer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mkitti
    - ngam
